### ISSUE TITLE
Cannot override onReset method of DateInput component

### ISSUE THREAD

**Issue by lilian-delouvy** [AxaFrance/react-toolkit#1002]
### Cannot override onReset method of DateInput component

![msedge_vKHHwpSYkf](https://user-images.githubusercontent.com/58565718/208856463-ace210df-9524-42b1-b718-7b5a40201821.gif)

#### Expected

The onReset method of DateInput should be either available to override, or should return the current day value and not display "jj/mm/aaaa".

#### Actual

It is impossible to override this method, and when you click on the reset button, no value is returned to the parent component, hence it is impossible to know when the user clicked on this button.

**Comment by EmmanuelDemey** [comment]
We implemented this way in order to be compliant with the previous version. But your solution was one of the solutions we had in mind. 

What do you think @arnaudforaison @johnmeunier  ?

**Comment by EmmanuelDemey** [comment]
@arnaudforaison @johnmeunier que pensez-vous du message de @lilian-delouvy ?

**Comment by MartinWeb** [comment]
We need to discuss this further to see which solution we would implement.

**Comment by Kubik-a** [comment]
I managed to do by settings the onInput event : 
` onInput={e => {
        if (!e.target.value) {
          // you can implement your logic here 
        }
      }}`
