### ISSUE TITLE
import fail with vite.js

### ISSUE THREAD

**Issue by guillaume-chervet** [AxaFrance/react-toolkit#1036]
I have the error bellow when i import the a package.

[plugin:vite:import-analysis] Failed to resolve entry for package "@axa-fr/react-toolkit-all". The package may have incorrect main/module/exports specified in its package.json.

this does not work with 2.0.0-alpha.11and 2.0.0.

![image](https://github.com/AxaFrance/react-toolkit/assets/52236059/6637347a-659c-43df-942d-5f0cceff80be)

Any idea ?

**Comment by MartinWeb** [comment]
I came across the same type of issue on github https://github.com/vitest-dev/vitest/issues/2922
And in the comment there's a link to a pull request on another project with a possible fix https://github.com/pagopa/io-services-cms/pull/40/files
Could be worth a try.

**Comment by MartinWeb** [comment]
This has possibly been fixed by this pull request https://github.com/AxaFrance/react-toolkit/pull/998
We will generate a new alpha soon with this.

@guillaume-chervet i will keep you updated to see if you can try it on the new alpha.

**Comment by MartinWeb** [comment]
@guillaume-chervet i just started a new project with vite and the toolkit in 2.0.0 version and i don't have any issue for now. Do you still have the problem ?

**Comment by MartinWeb** [comment]
Fix with the 2.1.0 version. I am closing this for now
