### ISSUE TITLE
[Title Bar] Augment bold for title

### ISSUE THREAD

**Issue by MartinWeb** [AxaFrance/react-toolkit#1170]
As of now the content of the title bar have a normal font-weight (400), but on the UX level it should be a bit bold (600).
This has been reviewed with UX of Slash.

Actual : 
![image](https://github.com/AxaFrance/react-toolkit/assets/1991349/f7527e0c-1c02-4af6-9072-8f73ead93825)

Expected : 
![image](https://github.com/AxaFrance/react-toolkit/assets/1991349/4f6e76a0-1487-4ce8-a6a2-db4cecb9cd3b)

**Comment by Railk** [comment]
Nickel côté UX.
Merci beaucoup
